const QueryKeys = {
  GAME: "GAME",
  SCORE: "SCORE",
  CURRENT_MINI_GAME: "CURRENT_MINI_GAME",
  MINIGAMES: {
    ABCD: {
      APPLIED_POWER_PLAYS: "MINIGAMES/ABCD/APPLIED_POWER_PLAYS",
      CATEGORIES: "MINIGAMES/ABCD/CATEGORIES",
      POWER_PLAYS: "MINIGAMES/ABCD/POWER_PLAYS",
      QUESTION: "MINIGAMES/ABCD/QUESTION",
      QUESTION_ANSWER: "MINIGAMES/ABCD/QUESTION_ANSWER",
      SELECTED_CATEGORY: "MINIGAMES/ABCD/SELECTED_CATEGORY",
    },
  },
};

export default QueryKeys;
